//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RbacUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RbacUser()
        {
            this.RbacUserParameters = new HashSet<RbacUserParameter>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int RoleId { get; set; }
    
        public virtual RbacRole RbacRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RbacUserParameter> RbacUserParameters { get; set; }
    }
}
