//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rbac> Rbacs { get; set; }
        public virtual DbSet<RbacRole> RbacRoles { get; set; }
        public virtual DbSet<RbacUser> RbacUsers { get; set; }
        public virtual DbSet<RbacUserParameter> RbacUserParameters { get; set; }
        public virtual DbSet<RbacLog> RbacLogs { get; set; }
    }
}
