//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RbacUserParameter
    {
        public int ParameterId { get; set; }
        public byte[] Name { get; set; }
        public byte[] Value { get; set; }
        public int UserId { get; set; }
    
        public virtual RbacUser RbacUser { get; set; }
    }
}
