//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rbac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rbac()
        {
            this.RbacRoles = new HashSet<RbacRole>();
        }
    
        public int RbacId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ConnectionString { get; set; }
        public byte[] Password { get; set; }
        public byte[] MetaDataRbac { get; set; }
        public byte[] MetaDataEntitlements { get; set; }
        public int Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RbacRole> RbacRoles { get; set; }
    }
}
