//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RbacLog
    {
        public int LogId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Query { get; set; }
        public string ParsedQuery { get; set; }
        public bool Parsed { get; set; }
        public string Errors { get; set; }
        public int RoleId { get; set; }
        public int UserId { get; set; }
        public string Source { get; set; }
        public Nullable<long> ElapsedTimeParseQuery { get; set; }
        public Nullable<long> ElapsedTimeConditionsNRelations { get; set; }
        public Nullable<long> ElapsedTimeApplyPermission { get; set; }
        public Nullable<long> ElapsedTimeApplyParameters { get; set; }
    
        public virtual RbacRole RbacRole { get; set; }
        public virtual RbacUser RbacUser { get; set; }
    }
}
