//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eyedia.Aarbac.Framework.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class RbacRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RbacRole()
        {
            this.RbacUsers = new HashSet<RbacUser>();
        }
    
        public int RoleId { get; set; }
        public int RbacId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] MetaDataRbac { get; set; }
        public byte[] MetaDataEntitlements { get; set; }
        public Nullable<int> Version { get; set; }
    
        public virtual Rbac Rbac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RbacUser> RbacUsers { get; set; }
    }
}
