USE [master]
GO

/****** Object:  Database [__DBNAME__]    Script Date: 11/1/2017 11:40:26 PM ******/
CREATE DATABASE [__DBNAME__] ON  PRIMARY 
( NAME = N'__DBNAME__', FILENAME = N'__DBFILE__' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'__DBNAME___log', FILENAME = N'__DBLOGFILE__' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [__DBNAME__] SET COMPATIBILITY_LEVEL = 100
GO

ALTER DATABASE [__DBNAME__] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [__DBNAME__] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [__DBNAME__] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [__DBNAME__] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [__DBNAME__] SET ARITHABORT OFF 
GO

ALTER DATABASE [__DBNAME__] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [__DBNAME__] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [__DBNAME__] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [__DBNAME__] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [__DBNAME__] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [__DBNAME__] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [__DBNAME__] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [__DBNAME__] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [__DBNAME__] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [__DBNAME__] SET  DISABLE_BROKER 
GO

ALTER DATABASE [__DBNAME__] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [__DBNAME__] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [__DBNAME__] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [__DBNAME__] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [__DBNAME__] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [__DBNAME__] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [__DBNAME__] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [__DBNAME__] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [__DBNAME__] SET  MULTI_USER 
GO

ALTER DATABASE [__DBNAME__] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [__DBNAME__] SET DB_CHAINING OFF 
GO

ALTER DATABASE [__DBNAME__] SET  READ_WRITE 
GO


